config/routes.rb
Kafekali::Application.routes.draw do

  resources :orders
  match 'purchases' => 'movements#index_purchase',         :via => :get, :as => :purchases
  match 'purchases' => 'movements#create_purchase',        :via => :post
  match 'purchases/new' => 'movements#new_purchase',       :via => :get, :as => :new_purchase
  match 'purchases/:id/edit' => 'movements#edit_purchase', :via => :get, :as => :edit_purchase
  match 'purchases/:id' => 'movements#show_purchase',      :via => :get, :as => :purchase
  match 'purchases/:id' => 'movements#update_purchase',    :via => :put
  match 'purchases/:id' => 'movements#destroy_purchase',   :via => :delete
  resources :movements
  resources :providers
  resources :products

end

app/models/movement.rb
class Movement < ActiveRecord::Base
  belongs_to :movement_type
  belongs_to :product
  belongs_to :provider
  belongs_to :order

  validates :product_id, :presence => true
  validates :provider_id, 
            :presence => true,
            :if => :validate_presence_of_provider_id
  validates :amount, 
            :presence => true,
            :numericality => { :greater_than => 0 }
  validates :movement_type_id, :presence => true

  private
  def validate_presence_of_provider_id
    # Required when movement is a purchase
    self.movement_type_id == 1 # 1 => Purchase
  end
end

app/models/movement_type.rb
class MovementType < ActiveRecord::Base
  has_many :movements

  scope :incomes, where(:is_income => true)
  scope :expenses, where(:is_income => false)
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  # GET /movements
  # GET /movements.json
  def index
    @movements = Movement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movements }
    end
  end

  # GET /movements/1
  # GET /movements/1.json
  def show
    @movement = Movement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movement }
    end
  end

  # GET /movements/new
  # GET /movements/new.json
  def new
    @movement = Movement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movement }
    end
  end

  # GET /movements/1/edit
  def edit
    @movement = Movement.find(params[:id])
  end

  # POST /movements
  # POST /movements.json
  def create
    @movement = Movement.new(params[:movement])

    respond_to do |format|
      if @movement.save
        format.html { redirect_to @movement, notice: 'Movement was successfully created.' }
        format.json { render json: @movement, status: :created, location: @movement }
      else
        format.html { render action: "new" }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movements/1
  # PUT /movements/1.json
  def update
    @movement = Movement.find(params[:id])

    respond_to do |format|
      if @movement.update_attributes(params[:movement])
        format.html { redirect_to @movement, notice: 'Movement was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1
  # DELETE /movements/1.json
  def destroy
    @movement = Movement.find(params[:id])
    @movement.destroy

    respond_to do |format|
      format.html { redirect_to movements_url }
      format.json { head :ok }
    end
  end

  # GET /purchases
  # GET /purchases.json
  def index_purchase
    # MovementType.first should refers to 'Purchases'
    @movements = MovementType.first.movements

    respond_to do |format|
      format.html # index_purchase.html.erb
      format.json { render json: @movements }
    end
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show_purchase
    @movement = Movement.find(params[:id])

    respond_to do |format|
      format.html # show_purchase.html.erb
      format.json { render json: @movement }
    end
  end

  # GET /purchases/new
  # GET /purchases/new.json
  def new_purchase
    @movement = Movement.new

    respond_to do |format|
      format.html # new_purchase.html.erb
    end
  end

  # GET /purchase/1/edit
  def edit_purchase
    @movement = Movement.find(params[:id])
  end

  # POST /purchases
  # POST /purchases.json
  def create_purchase
    @movement = Movement.new(params[:purchase])

    respond_to do |format|
      if @movement.save
        format.html { redirect_to purchase_path(@movement), notice: 'Purchase was successfully created.' }
        format.json { render json: @movement, status: :created, location: @movement }
      else
        format.html { render action: 'new_purchase' }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /purchases/1
  # PUT /purchases/1.json
  def update_purchase
    @movement = Movement.find(params[:id])

    respond_to do |format|
      if @movement.update_attributes(params[:purchase])
        format.html { redirect_to purchase_path(@movement), notice: 'Purchase was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit_purchase" }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy_purchase
    @movement = Movement.find(params[:id])
    @movement.destroy

    respond_to do |format|
      format.html { redirect_to purchases_url }
      format.json { head :ok }
    end
  end

end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/movements/_form.html.erb
<%= form_for(@movement) do |f| %>
  <% if @movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
      <% @movement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.collection_select(:product_id, Product.all, :id, :friendly_label) %>
  </div>

  <div class="field">
    <%= f.label :provider_id %><br />
    <%= f.collection_select(:provider_id, Provider.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :movement_type_id %><br />
    <%= f.select :movement_type_id, options_from_collection_for_select(MovementType.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movements/_purchase_form.html.erb
<%= form_for(@movement, :as => :purchase, :url => purchases_path ) do |f| %>
  <% if @movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
      <% @movement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.collection_select(:product_id, Product.all, :id, :friendly_label, :include_blank => true) %>
  </div>

  <div class="field">
    <%= f.label :provider_id %><br />
    <%= f.collection_select(:provider_id, Provider.all, :id, :name, :include_blank => true) %>
  </div>

  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :movement_type_id %><br />
    <%= f.collection_select :movement_type_id, MovementType.incomes, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movements/edit.html.erb
<h1>Editing movement</h1>

<%= render 'form' %>

<%= link_to 'Show', @movement %> |
<%= link_to 'Back', movements_path %>

app/views/movements/edit_purchase.html.erb
<h1>Editing purchase</h1>

<%= render 'purchase_form' %>

<%= link_to 'Show', @movement %> |
<%= link_to 'Back', movements_path %>

app/views/movements/index.html.erb
<h1>Listing movements</h1>

<table>
  <tr>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movements.each do |movement| %>
  <tr>
    <td><%= movement.note %></td>
    <td><%= link_to 'Show', movement %></td>
    <td><%= link_to 'Edit', edit_movement_path(movement) %></td>
    <td><%= link_to 'Destroy', movement, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movement', new_movement_path %>

app/views/movements/index_purchase.html.erb
<h1>Listing purchases</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Amount</th>
    <th>Provider</th>
    <th>Created at</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movements.each do |purchase| %>
  <tr>
    <td><%= purchase.product.friendly_label %></td>
    <td><%= purchase.amount %></td>
    <td><%= purchase.provider.name %></td>
    <td><%= purchase.created_at %></td>
    <td><%= purchase.note %></td>
    <td><%= link_to 'Show', purchase_path(purchase) %></td>
    <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
    <td><%= link_to 'Destroy', purchase_path(purchase), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Purchase', new_purchase_path %>

app/views/movements/new.html.erb
<h1>New movement</h1>

<%= render 'form' %>

<%= link_to 'Back', movements_path %>

app/views/movements/new_purchase.html.erb
<h1>New purchase</h1>

<%= render 'purchase_form' %>

<%= link_to 'Back', movements_path %>

app/views/movements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Note:</b>
  <%= @movement.note %>
</p>


<%= link_to 'Edit', edit_movement_path(@movement) %> |
<%= link_to 'Back', movements_path %>

app/views/movements/show_purchase.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @movement.product.friendly_label %>
</p>

<p>
  <b>Amount:</b>
  <%= @movement.amount %>
</p>

<p>
  <b>Provider:</b>
  <%= @movement.provider.name %>
</p>

<p>
  <b>Note:</b>
  <%= @movement.note %>
</p>

<%= link_to 'Edit', edit_purchase_path(@movement) %> |
<%= link_to 'Back', purchases_path %>